name: xeus-python-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - pip:
      - jupyterlite-javascript-kernel
      - jupyterlite-pyodide-kernel
      - jupyterlite-p5-kernel